version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - 9400:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=eka-cluster
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ekadata:/usr/share/elasticsearch/data
    command:
      - sh
      - -c
      - "./bin/elasticsearch-plugin install --silent analysis-icu; docker-entrypoint.sh"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:7.9.0
    ports:
      - 8200:8200
      - 8201:8200
    environment:
      - apm-server.host=0.0.0.0
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9400"]
    depends_on:
      - elasticsearch
      - kibana

volumes:
  ekadata:
    driver: local
